config/routes.rb
UnitConverter::Application.routes.draw do
  require 'api_constraints'

  root 'home#index'

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do
      post 'convert_forward', to: 'conversions#convert_forward'
      post 'convert_backward', to: 'conversions#convert_backward'
      post 'change_measurement', to: 'conversions#change_measurement'
    end

  end


end

app/models/conversion.rb
class Conversion < ActiveRecord::Base

  belongs_to :source_unit, :class_name => 'Unit'
  belongs_to :target_unit, :class_name => 'Unit'
  belongs_to :measurement_type

  validates :forward_formula, :presence => true
  validates :backward_formula, :presence => true
  validates :measurement_type, :presence => true


  def forward_conversion(input)
    return "Please enter a numeric value" unless is_numerical?(input)
    begin
      input = Float(input)
      eval(forward_formula).round(6)
    rescue
      return "Incorrect Formula"
    end
  end

  def backward_conversion(input)
    return "Please enter a numeric value" unless is_numerical?(input)
    begin
      input = Float(input)
      eval(backward_formula).round(6)
    rescue
      "Incorrect Formula"
    end
  end

  def is_numerical?(input)
    true if Float(input) rescue false
  end

  def forward_formula_name
    "#{source_unit.name} to #{target_unit.name}"
  end

  def backward_formula_name
    "#{target_unit.name} to #{source_unit.name}"
  end


end

app/models/measurement_type.rb
class MeasurementType < ActiveRecord::Base

  validates :name, {:presence => true}
  validates :name, :uniqueness => {:case_sensitive => false }

  has_many :units, :dependent => :destroy
  has_many :conversions

end

app/models/unit.rb
class Unit < ActiveRecord::Base

  belongs_to :measurement_type
  has_many :conversions, :finder_sql => proc {"SELECT * from conversions WHERE source_unit_id = #{self.id} OR target_unit_id = #{self.id};"}, :dependent => :destroy

  validates :name,:measurement_type, :presence => true
  validates :name, :uniqueness => {:case_sensitive => false }

end

app/controllers/api/v1/conversions_controller.rb
module Api
  module V1
    class ConversionsController < ApplicationController
      before_filter :get_conversion, except: :change_measurement
      respond_to :json

      def convert_forward
          @result = @conversion.forward_conversion(params[:value].to_f)
          render_response(@result)
      end

      def convert_backward
          @result = @conversion.backward_conversion(params[:value].to_f)
          render_response(@result)
      end

      def change_measurement
        @measurement_type = MeasurementType.find(params[:id])
        conversion = @measurement_type.conversions.first
        data = {source_unit_name: conversion.source_unit,target_unit_name: conversion.target_unit}
        render_response(data)
      end

      def render_response(result)
        respond_to do |format|
          format.json { render :json => result }
        end
      end

      def get_conversion
        @conversion = Conversion.find(params[:id])
      end

    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

    @measurement_types = MeasurementType.all
    @measurement_type = MeasurementType.first
    @conversion = @measurement_type.conversions.first

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="main_box">
  <h1>Unit converter</h1>

  <div class="conversion_frame">

    <%= select_tag(:measurement_type_id, options_from_collection_for_select(@measurement_types, :id, :name),
                   class: "google_style", action:  api_change_measurement_path) %>

    <div class="unit_box">
      <input class="unit forward" data-action="forward" data-url="<%= api_convert_forward_path %> " />

    </div>
    <div class="equal">=</div>
    <div class="unit_box">
      <input class="unit backward"  data-action="backward"  data-url="<%= api_convert_backward_path %>" />

    </div>

    <label id="unit_name_forward" for="source_unit" class="unit_name"><%= @conversion.source_unit.name %></label>
    <label id="unit_name_backward" for="target_unit" class="unit_name"><%= @conversion.target_unit.name %></label>

  </div>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UnitConverter</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>